const express = require('express');
const router = express.Router();
const { getTeacherProfile, uploadAttendance, getUploadedAttendance } = require('../controllers/teacherController.js');
const teacherSubController = require('../controllers/teacherSubController');
const teacherSubStudentController = require('../controllers/teacherSubStudentController');
const teacherMarksController = require('../controllers/teacherMarksController.js');
const marksController = require('../controllers/marksBelowController');
const teacherUpdateMarksController = require('../controllers/teacherUpdateMarksController');
const teachUpdateAttendanceController = require('../controllers/teachUpdateAttendanceController');
const { getAttendanceByDateRange } = require('../controllers/fromToRangeController');
const { fetchAttendanceAndMarks } = require('../controllers/attenMarksController');
const { getTotalLectures, getUpdatedLast } = require('../controllers/totalLectureController');
const attendanceController = require('../controllers/attendanceBelowController');
const { teacher } = require('../middleware/isAllowed');

router.get('/attendance/below-threshold', teacher, attendanceController.getStudentsBelowAttendanceThreshold);
router.get('/atten/marks', teacher, fetchAttendanceAndMarks);
router.get('/total-lectures', teacher, getTotalLectures);
router.get('/updated-last', teacher, getUpdatedLast);
router.get('/profile', teacher, getTeacherProfile);
router.get('/subjects', teacher, teacherSubController.getSubjectsByTeacher);
router.get('/subject-students', teacher, teacherSubStudentController.getStudentsBySubject);
router.post('/attendance/upload', teacher, uploadAttendance);
router.get('/attendance/get', teacher, getUploadedAttendance);
router.put('/attendance/update', teacher, teachUpdateAttendanceController.updateAttendance);
router.get('/attendance/range', teacher, getAttendanceByDateRange);
router.post('/marks/upload', teacher, teacherMarksController.uploadMarks);
router.get('/marks', teacher, teacherMarksController.getMarks);
router.put('/marks/update', teacher, teacherUpdateMarksController.updateMarks);
router.get('/students/below-threshold', teacher, marksController.getStudentsBelowThreshold);

module.exports = router;
