const express = require('express');
const router = express.Router();
const { getTeacherProfile, uploadAttendance, getUploadedAttendance } = require('../controllers/teacherController.js');
const teacherSubController = require('../controllers/teacherSubController');
const teacherSubStudentController = require('../controllers/teacherSubStudentController');
const teacherMarksController = require('../controllers/teacherMarksController.js');
const marksController = require('../controllers/marksBelowController');
const teacherUpdateMarksController = require('../controllers/teacherUpdateMarksController');
const teachUpdateAttendanceController = require('../controllers/teachUpdateAttendanceController');
const { getAttendanceByDateRange } = require('../controllers/fromToRangeController');
const { fetchAttendanceAndMarks } = require('../controllers/attenMarksController');
const { getTotalLectures, getUpdatedLast } = require('../controllers/totalLectureController');
const attendanceController = require('../controllers/attendanceBelowController');
const { teacher } = require('../middleware/isAllowed');

router.use(teacher);
router.get('/attendance/below-threshold', attendanceController.getStudentsBelowAttendanceThreshold);
router.get('/atten/marks', fetchAttendanceAndMarks);
router.get('/total-lectures', getTotalLectures);
router.get('/updated-last', getUpdatedLast);
router.get('/profile', getTeacherProfile);
router.get('/subjects', teacherSubController.getSubjectsByTeacher);
router.get('/subject-students', teacherSubStudentController.getStudentsBySubject);
router.post('/attendance/upload', uploadAttendance);
router.get('/attendance/get', getUploadedAttendance);
router.put('/attendance/update', teachUpdateAttendanceController.updateAttendance);
router.get('/attendance/range', getAttendanceByDateRange);
router.post('/marks/upload', teacherMarksController.uploadMarks);
router.get('/marks', teacherMarksController.getMarks);
router.put('/marks/update', teacherUpdateMarksController.updateMarks);
router.get('/students/below-threshold', marksController.getStudentsBelowThreshold);

module.exports = router;
